config/routes.rb
Rails.application.routes.draw do
    get 'goods/search'
    root to: 'goods#search'
    
    get 'login', to: 'sessions#new'
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy'
    
    get 'signup', to: 'users#new'
    resources :users, only: [:show, :create] 
    resources :items, only: [:create, :destroy]  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  
  validates :image_url, presence: true, length: { maximum: 255 }
  validates :name, presence: true, length: { maximum: 255 }
  validates :url, presence: true, length: { maximum: 255 }
  validates :price, presence: true, length: { maximum: 255 }
  validates :item_code, presence: true, length: { maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                      uniqueness: { case_sensitive: false }
    has_secure_password
    
    has_many :items
    has_many :wish_items, through: :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    include SessionsHelper
    include Pagy::Backend
    
    private

    def require_user_logged_in
      unless logged_in?
      redirect_to login_url
      end
    end
    
    def counts(user)
        @count_wish_items = user.wish_items.count
    end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  def search
    if params[:keyword] && params[:keyword].length <= 1 
       flash.now[:danger] = '2文字以上入力してください'
    elsif params[:keyword]
      @goods = RakutenWebService::Ichiba::Item.search(keyword: params[:keyword])
      
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :login_check, only: [:create]
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  before_action :registered, only: [:create]
    
  def create
    item = current_user.items.build(item_params)
    if item.save
      flash[:success] = 'リストに追加しました'
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = 'リストへの追加に失敗しました'
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @item.destroy
    flash[:success] = 'リストから削除しました'
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  def login_check
    unless logged_in?
      flash[:danger] = "リストに追加できるのはログインユーザーのみです"
      redirect_to login_path
    end
  end
  
  def registered
    if current_user.items.find_by(item_code: params[:item][:item_code])
      flash[:danger] = 'リストに登録済みのアイテムです'
      redirect_back(fallback_location: root_path)
    end
  end
  
  # Strong Parameter
  def item_params
    params.require(:item).permit(:image_url, :name, :url, :price, :item_code)
  end
  
  def correct_user
    @item = current_user.items.find_by(id: params[:id])
    unless @item
      redirect_to root_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    render :new
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
  before_action :require_user_logged_in, only: [:index, :show]
  before_action :correct_user, only: [:show] 
  
  def index
   
  end

  def show
    @user = User.find(params[:id])
    @items = current_user.items
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def likes
    @user = User.find(params[:id])
    @pagy, @wish_items = pagy(@user.wish_items)
    counts(@user)
  end
  
  private
  
  def correct_user
    if  current_user.id.to_s != params[:id]
        flash[:danger] = 'アクセス権がありません'
        redirect_to root_url
    end
  end
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    #!!current_user
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  end
end

app/views/goods/_good.html.erb
<% @goods.first(10).each do |good| %>
<div class="container">
    <div class="row">
        <div class="col-md-2 my-1 border-bottom 1px"><%= image_tag(good['mediumImageUrls'][0], alt:good.name) %></div>
        <div class="col-md-6 my-1 border-bottom 1px"><%= link_to good.name, "#{good.url}" %></div>
        <div class="col-md-2 my-1 border-bottom 1px">価格：<%= number_with_delimiter(good.price) %>円</div>
        <div class="col-md-2 my-1 border-bottom 1px"><%= form_with(url:items_path, scope: :item) do |f| %>
        <%= f.hidden_field :image_url, value: good['mediumImageUrls'][0],id: "good_imageurl_#{good.code}" %>
        <%= f.hidden_field :name, value: good.name, id: "good_name_#{good.code}"%>
        <%= f.hidden_field :url, value: good.url, id: "good_url_#{good.code}"%>
        <%= f.hidden_field :price, value: good.price, id: "good_price_#{good.code}"%>
        <%= f.hidden_field :item_code, value: good.code, id: "good_item_code_#{good.code}"%>
        <%= f.submit 'Add Your Wishlist', class: 'mx-1 btn btn-success btn-sm' %>
        <% end %></div>
    </div>
</div>
<% end %>

app/views/goods/search.html.erb
<div class="bg-dark text-white p-3 p-sm-5 my-4 rounded">
  <div class="text-center">
    <h1>Welcome to Wishlist ! </h1>
    <h2>製品名を入力して検索しよう</h2>
    <div class="form-group">
        <div class="search-box">
            <%= form_with url: goods_search_path, method: :get, local: true do |f| %>
                
            <%= f.text_field :keyword, value: params[:keyword], class: "form-control" %>
            <%= f.submit '製品名を検索', class: "my-2 form-control btn btn-secondary" %>
            <% end %>
        </div>
    </div>
  </div>
</div>
<div class="container">
<% if @goods.present? %>
  <%= render 'goods/good' %>
<% end %>
</div>

app/views/items/_add_button.html.erb
<%= form_with(model: current_user.favorites.build) do |f| %>
      <%= hidden_field_tag :image_url, ['mediumImageUrls'][0] %>
      <%= hidden_field_tag :name, good.name %>
      <%= hidden_field_tag :url, good.url %>
      <%= hidden_field_tag :price, good.price %>
      <%= hidden_field_tag :item_code, good.code %>
      <%= f.submit 'Add Your Wishlist', class: 'mx-1 btn btn-success btn-sm' %>
    <% end %>
  <% end %>

app/views/items/_items.html.erb
<% if items.any? %>
<% items.each do |item| %>
<div class="row">
    <div class="col-md-3"><%= image_tag(item.image_url, alt:item.name) %></div>
    <div class="col-md-5"><%= link_to item.name, "#{item.url}" %></div>
    <div class="col-md-3">価格：<%= number_with_delimiter(item.price) %>円</div>
    <div class="col-md-1"><%=  link_to "Delete", item, method: :delete, data: { confirm: "You sure?" }, class: 'btn btn-danger btn-sm' %></div>
</div>
<% end %>
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container-fluid ps-5 pe-5">
      <a class="navbar-brand" href="/">Wishlist</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <% if logged_in? %>
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to 'Wishlist', user_path(current_user), class: 'nav-link' %></li>
        </ul>
        <div class="btn-group">
          <button type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><%= current_user.name %></button>
          <ul class="dropdown-menu dropdown-menu-end">
            <li class="dropdown-divider"></li>
            <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %></li>
          </ul>
        </div>
        <% else %>
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
        </ul>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Wishlist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body data-turbolinks="false">
    <%= render 'layouts/navbar' %>
    
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      
    <%= yield %>
    </div>
  </body>
</html>

app/views/users/_users.html.erb
<% if users.any? %>
  <ul class="list-unstyled">
    <% users.each do |user| %>
      <li class="mb-3 d-flex">
        <img class="rounded me-2" src="<%= gravatar_url(user, { size: 64 }) %>" alt="">
        <div>
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user), class: "text-decoration-none" %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
  <%== pagy_bootstrap_nav(@pagy) %>
<% end %>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

      <div class="mb-3">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary w-100' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
  </aside>
  <div class="col-md-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item">Wishlist</li>
    </ul>
    <%= render 'items/items', items: @items %>
  </div>
</div>